version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brandastronauts-app
    restart: always
    ports:
      - "127.0.0.1:3019:80"
    environment:
      - NODE_ENV=production
