/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'page-overrides': PageOverride;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'page-overrides': PageOverridesSelect<false> | PageOverridesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'footer-settings': FooterSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'footer-settings': FooterSettingsSelect<false> | FooterSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS administrators for content editing access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage images used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Edit any website page. Set the URL Path (e.g. /methodology/innovation), then add sections from the block library. If you leave the sections empty, the page falls back to its built-in design — perfect for incremental editing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-overrides".
 */
export interface PageOverride {
  id: string;
  /**
   * Editor-friendly name shown only in CMS.
   */
  internalName: string;
  /**
   * Must exactly match the route used on the website.
   */
  pathname: string;
  /**
   * Add, remove, and reorder sections. Section types map directly to existing frontend components.
   */
  sections?:
    | (
        | {
            id?: string | null;
            variant?: ('stark' | 'precision' | 'publication' | 'archive') | null;
            headline: string;
            subheadline?: string | null;
            breadcrumb?:
              | {
                  label: string;
                  path?: string | null;
                  id?: string | null;
                }[]
              | null;
            primaryCta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            secondaryCta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            image?: {
              asset?: (string | null) | Media;
              /**
               * Use this only when not uploading to Media Library.
               */
              src?: string | null;
              alt?: string | null;
              privacyBlur?: boolean | null;
              caption?: string | null;
            };
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            id?: string | null;
            text: string;
            /**
             * Add, remove, and reorder items.
             */
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'ticker';
          }
        | {
            id?: string | null;
            header: string;
            intro?: string | null;
            /**
             * Add, remove, and reorder cards.
             */
            items?:
              | {
                  title: string;
                  icon?: string | null;
                  body?: string | null;
                  cta?: {
                    label?: string | null;
                    /**
                     * Use /path for internal pages, or https:// for external links.
                     */
                    href?: string | null;
                    external?: boolean | null;
                    disabled?: boolean | null;
                    download?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'grid3';
          }
        | {
            id?: string | null;
            header: string;
            intro?: string | null;
            variant?: ('blogGrid' | 'profiles' | 'newsGrid' | 'pressRoom') | null;
            /**
             * Add, remove, and reorder cards by drag-and-drop.
             */
            cards?:
              | {
                  tag?: string | null;
                  headline: string;
                  meta?: string | null;
                  body?: string | null;
                  icon?: string | null;
                  image?: {
                    asset?: (string | null) | Media;
                    /**
                     * Use this only when not uploading to Media Library.
                     */
                    src?: string | null;
                    alt?: string | null;
                    privacyBlur?: boolean | null;
                    caption?: string | null;
                  };
                  action?: {
                    label?: string | null;
                    /**
                     * Use /path for internal pages, or https:// for external links.
                     */
                    href?: string | null;
                    external?: boolean | null;
                    disabled?: boolean | null;
                    download?: boolean | null;
                  };
                  secondaryAction?: {
                    label?: string | null;
                    disabled?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            id?: string | null;
            sectionName?: string | null;
            header: string;
            intro?: string | null;
            items?:
              | {
                  title: string;
                  meta?: string | null;
                  description?: string | null;
                  statusLine?: string | null;
                  id?: string | null;
                }[]
              | null;
            cta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            id?: string | null;
            sectionName?: string | null;
            header: string;
            intro?: string | null;
            cards?:
              | {
                  status?: string | null;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            cta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            blockName?: string | null;
            blockType: 'libraryCards';
          }
        | {
            id?: string | null;
            header: string;
            intro?: string | null;
            /**
             * Add, remove, and reorder FAQ rows.
             */
            items?:
              | {
                  q: string;
                  a: string;
                  id?: string | null;
                }[]
              | null;
            footerCta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            blockName?: string | null;
            blockType: 'accordion';
          }
        | {
            id?: string | null;
            header?: string | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'statsBar';
          }
        | {
            id?: string | null;
            heading?: string | null;
            title?: string | null;
            body?: string | null;
            /**
             * Add, remove, and reorder items.
             */
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'compact') | null;
            cta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            blockName?: string | null;
            blockType: 'highlightBox';
          }
        | {
            id?: string | null;
            header: string;
            items?:
              | {
                  year?: string | null;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            id?: string | null;
            heading?: string | null;
            header?: string | null;
            intro?: string | null;
            /**
             * Add, remove, and reorder items.
             */
            columns?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Add, remove, and reorder items.
             */
            headers?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            rows?:
              | {
                  label?: string | null;
                  /**
                   * Add, remove, and reorder items.
                   */
                  values?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'comparisonTable';
          }
        | {
            id?: string | null;
            header: string;
            items?:
              | {
                  size?: ('sm' | 'md' | 'lg') | null;
                  tag?: string | null;
                  headline: string;
                  body?: string | null;
                  image?: {
                    asset?: (string | null) | Media;
                    /**
                     * Use this only when not uploading to Media Library.
                     */
                    src?: string | null;
                    alt?: string | null;
                    privacyBlur?: boolean | null;
                    caption?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'bento';
          }
        | {
            id?: string | null;
            header?: string | null;
            intro?: string | null;
            logos?:
              | {
                  name: string;
                  asset?: (string | null) | Media;
                  src?: string | null;
                  alt?: string | null;
                  role?: string | null;
                  collaboration?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'logoStrip';
          }
        | {
            id?: string | null;
            header: string;
            cards?:
              | {
                  title: string;
                  icon?: string | null;
                  description?: string | null;
                  image?: string | null;
                  button?: {
                    label?: string | null;
                    /**
                     * Use /path for internal pages, or https:// for external links.
                     */
                    href?: string | null;
                    external?: boolean | null;
                    disabled?: boolean | null;
                    download?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            footerNote?: string | null;
            blockName?: string | null;
            blockType: 'buttonCards';
          }
        | {
            id?: string | null;
            header: string;
            intro?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  format?: string | null;
                  size?: string | null;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'downloadList';
          }
        | {
            id?: string | null;
            sectionName?: string | null;
            header: string;
            body: string;
            variant?: ('default' | 'muted') | null;
            cta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            id?: string | null;
            header: string;
            intro?: string | null;
            description?: string | null;
            fields?:
              | {
                  name: string;
                  label: string;
                  type?: ('text' | 'email' | 'tel' | 'textarea' | 'select') | null;
                  placeholder?: string | null;
                  required?: boolean | null;
                  /**
                   * Add, remove, and reorder items.
                   */
                  options?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            submitLabel?: string | null;
            submit?: {
              to?: string | null;
              subject?: string | null;
              successMessage?: string | null;
            };
            contactNote?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            blockName?: string | null;
            blockType: 'form';
          }
        | {
            id?: string | null;
            header: string;
            layout?: ('default' | 'mainLarge') | null;
            main: {
              tag?: string | null;
              headline: string;
              excerpt?: string | null;
              image?: {
                asset?: (string | null) | Media;
                /**
                 * Use this only when not uploading to Media Library.
                 */
                src?: string | null;
                alt?: string | null;
                privacyBlur?: boolean | null;
                caption?: string | null;
              };
              cta?: {
                label?: string | null;
                /**
                 * Use /path for internal pages, or https:// for external links.
                 */
                href?: string | null;
                external?: boolean | null;
                disabled?: boolean | null;
                download?: boolean | null;
              };
            };
            side?:
              | {
                  tag?: string | null;
                  headline: string;
                  excerpt?: string | null;
                  image?: {
                    asset?: (string | null) | Media;
                    /**
                     * Use this only when not uploading to Media Library.
                     */
                    src?: string | null;
                    alt?: string | null;
                    privacyBlur?: boolean | null;
                    caption?: string | null;
                  };
                  cta?: {
                    label?: string | null;
                    /**
                     * Use /path for internal pages, or https:// for external links.
                     */
                    href?: string | null;
                    external?: boolean | null;
                    disabled?: boolean | null;
                    download?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'featuredStories';
          }
        | {
            id?: string | null;
            header: string;
            columns?:
              | {
                  title: string;
                  sub?: string | null;
                  body?: string | null;
                  badge?: string | null;
                  cta?: {
                    label?: string | null;
                    /**
                     * Use /path for internal pages, or https:// for external links.
                     */
                    href?: string | null;
                    external?: boolean | null;
                    disabled?: boolean | null;
                    download?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            id?: string | null;
            sectionName?: string | null;
            header: string;
            intro?: string | null;
            body?: string | null;
            cta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            items?:
              | {
                  tag?: string | null;
                  title: string;
                  caption?: string | null;
                  image?: {
                    asset?: (string | null) | Media;
                    /**
                     * Use this only when not uploading to Media Library.
                     */
                    src?: string | null;
                    alt?: string | null;
                    privacyBlur?: boolean | null;
                    caption?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'galleryGrid';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'sitemap';
          }
        | {
            id?: string | null;
            /**
             * Drag and drop to reorder.
             */
            items?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'metaStrip';
          }
        | {
            id?: string | null;
            header?: string | null;
            intro?: string | null;
            variant?: ('default' | 'comparison') | null;
            compact?: boolean | null;
            left?: {
              heading?: string | null;
              icon?: string | null;
              lead?: string | null;
              items?:
                | {
                    label?: string | null;
                    text?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            right?: {
              heading?: string | null;
              icon?: string | null;
              lead?: string | null;
              items?:
                | {
                    label?: string | null;
                    text?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            footer?: string | null;
            cta?: {
              label?: string | null;
              /**
               * Use /path for internal pages, or https:// for external links.
               */
              href?: string | null;
              external?: boolean | null;
              disabled?: boolean | null;
              download?: boolean | null;
            };
            blockName?: string | null;
            blockType: 'twoColumn';
          }
        | {
            id?: string | null;
            header?: string | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: string | null;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'relatedCards';
          }
        | {
            header: string;
            intro?: string | null;
            filterNote?: string | null;
            patents?:
              | {
                  title: string;
                  category?: string | null;
                  status?: string | null;
                  filingDate?: string | null;
                  ageGroup?: string | null;
                  applicationNo?: string | null;
                  inventors?: string | null;
                  description?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'patentGrid';
          }
        | {
            id?: string | null;
            name: string;
            role?: string | null;
            email?: string | null;
            image?: {
              asset?: (string | null) | Media;
              /**
               * Use this only when not uploading to Media Library.
               */
              src?: string | null;
              alt?: string | null;
              privacyBlur?: boolean | null;
              caption?: string | null;
            };
            bio?: string | null;
            socials?:
              | {
                  type?: string | null;
                  label?: string | null;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'profile';
          }
        | {
            header: string;
            items?:
              | {
                  term: string;
                  definition: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'glossaryAccordion';
          }
        | {
            id?: string | null;
            header: string;
            items?:
              | {
                  number: string;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'numberedCards';
          }
        | {
            header: string;
            tiers?:
              | {
                  label?: string | null;
                  title: string;
                  subtitle?: string | null;
                  body?: string | null;
                  /**
                   * Add, remove, and reorder items.
                   */
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  note?: string | null;
                  cta?: {
                    label?: string | null;
                    /**
                     * Use /path for internal pages, or https:// for external links.
                     */
                    href?: string | null;
                    external?: boolean | null;
                    disabled?: boolean | null;
                    download?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tierCards';
          }
        | {
            header: string;
            tools?:
              | {
                  title: string;
                  subtitle?: string | null;
                  body?: string | null;
                  /**
                   * Add, remove, and reorder items.
                   */
                  details?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  downloads?:
                    | {
                        label: string;
                        href: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'toolCards';
          }
        | {
            header: string;
            intro?: string | null;
            body?: string | null;
            /**
             * Add, remove, and reorder items.
             */
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklist';
          }
        | {
            id?: string | null;
            header: string;
            intro?: string | null;
            /**
             * Add, remove, and reorder items.
             */
            headers?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            rows?:
              | {
                  /**
                   * Add, remove, and reorder items.
                   */
                  cells?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'tableBlock';
          }
        | {
            id?: string | null;
            header?: string | null;
            body?: string | null;
            blockName?: string | null;
            blockType: 'anchorBlock';
          }
        | {
            header: string;
            steps?:
              | {
                  title: string;
                  body?: string | null;
                  /**
                   * Add, remove, and reorder items.
                   */
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timelineSteps';
          }
        | {
            header: string;
            items?:
              | {
                  title: string;
                  icon?: string | null;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pillars';
          }
        | {
            id?: string | null;
            header: string;
            papers?:
              | {
                  title: string;
                  doi?: string | null;
                  link?: string | null;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'frameworkPapers';
          }
        | {
            id?: string | null;
            title: string;
            subtitle?: string | null;
            classification?: string | null;
            /**
             * Drag and drop to reorder.
             */
            dataPanel?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'dossierHeader';
          }
        | {
            id?: string | null;
            number?: string | null;
            label?: string | null;
            header: string;
            body: string;
            variant?: ('default' | 'abstract') | null;
            blockName?: string | null;
            blockType: 'dossierSection';
          }
        | {
            id?: string | null;
            quote: string;
            blockName?: string | null;
            blockType: 'dossierQuoteStrip';
          }
        | {
            id?: string | null;
            number?: string | null;
            label?: string | null;
            header?: string | null;
            rows?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'dossierSpecTable';
          }
        | {
            id?: string | null;
            number?: string | null;
            label?: string | null;
            events?:
              | {
                  date: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'dossierTimeline';
          }
        | {
            id?: string | null;
            label?: string | null;
            body: string;
            blockName?: string | null;
            blockType: 'dossierNotice';
          }
        | {
            id?: string | null;
            number?: string | null;
            label?: string | null;
            header?: string | null;
            intro?: string | null;
            principles?:
              | {
                  number?: string | null;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            conclusion?: string | null;
            blockName?: string | null;
            blockType: 'dossierPrinciples';
          }
        | {
            id?: string | null;
            number?: string | null;
            label?: string | null;
            images?:
              | {
                  asset?: (string | null) | Media;
                  src?: string | null;
                  alt?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'dossierGallery';
          }
        | {
            id?: string | null;
            body: string;
            blockName?: string | null;
            blockType: 'dossierArchiveNotice';
          }
        | {
            id?: string | null;
            header?: string | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: string | null;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'dossierRelated';
          }
      )[]
    | null;
  stickyCta?: {
    label?: string | null;
    href?: string | null;
    type?: ('download' | 'link') | null;
  };
  pageTitle?: string | null;
  /**
   * Used when SEO description is not set.
   */
  metaDescription?: string | null;
  /**
   * Editorial reference date for this page override.
   */
  publishedAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
    keywords?: string | null;
    robots?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogType?: ('website' | 'article') | null;
    ogImage?: (string | null) | Media;
    ogImageUrl?: string | null;
    ogImageAlt?: string | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    twitterImageUrl?: string | null;
  };
  /**
   * Advanced: add one JSON object per schema node. These are rendered as JSON-LD on this page.
   */
  schemas?:
    | {
        label?: string | null;
        schema:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'page-overrides';
        value: string | PageOverride;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-overrides_select".
 */
export interface PageOverridesSelect<T extends boolean = true> {
  internalName?: T;
  pathname?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              id?: T;
              variant?: T;
              headline?: T;
              subheadline?: T;
              breadcrumb?:
                | T
                | {
                    label?: T;
                    path?: T;
                    id?: T;
                  };
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              image?:
                | T
                | {
                    asset?: T;
                    src?: T;
                    alt?: T;
                    privacyBlur?: T;
                    caption?: T;
                  };
              blockName?: T;
            };
        ticker?:
          | T
          | {
              id?: T;
              text?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        grid3?:
          | T
          | {
              id?: T;
              header?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    body?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                          disabled?: T;
                          download?: T;
                        };
                    id?: T;
                  };
              blockName?: T;
            };
        cards?:
          | T
          | {
              id?: T;
              header?: T;
              intro?: T;
              variant?: T;
              cards?:
                | T
                | {
                    tag?: T;
                    headline?: T;
                    meta?: T;
                    body?: T;
                    icon?: T;
                    image?:
                      | T
                      | {
                          asset?: T;
                          src?: T;
                          alt?: T;
                          privacyBlur?: T;
                          caption?: T;
                        };
                    action?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                          disabled?: T;
                          download?: T;
                        };
                    secondaryAction?:
                      | T
                      | {
                          label?: T;
                          disabled?: T;
                        };
                    id?: T;
                  };
              blockName?: T;
            };
        list?:
          | T
          | {
              id?: T;
              sectionName?: T;
              header?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    meta?: T;
                    description?: T;
                    statusLine?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              blockName?: T;
            };
        libraryCards?:
          | T
          | {
              id?: T;
              sectionName?: T;
              header?: T;
              intro?: T;
              cards?:
                | T
                | {
                    status?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              blockName?: T;
            };
        accordion?:
          | T
          | {
              id?: T;
              header?: T;
              intro?: T;
              items?:
                | T
                | {
                    q?: T;
                    a?: T;
                    id?: T;
                  };
              footerCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              blockName?: T;
            };
        statsBar?:
          | T
          | {
              id?: T;
              header?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        highlightBox?:
          | T
          | {
              id?: T;
              heading?: T;
              title?: T;
              body?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              variant?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              blockName?: T;
            };
        timeline?:
          | T
          | {
              id?: T;
              header?: T;
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        comparisonTable?:
          | T
          | {
              id?: T;
              heading?: T;
              header?: T;
              intro?: T;
              columns?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              headers?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    label?: T;
                    values?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              blockName?: T;
            };
        bento?:
          | T
          | {
              id?: T;
              header?: T;
              items?:
                | T
                | {
                    size?: T;
                    tag?: T;
                    headline?: T;
                    body?: T;
                    image?:
                      | T
                      | {
                          asset?: T;
                          src?: T;
                          alt?: T;
                          privacyBlur?: T;
                          caption?: T;
                        };
                    id?: T;
                  };
              blockName?: T;
            };
        logoStrip?:
          | T
          | {
              id?: T;
              header?: T;
              intro?: T;
              logos?:
                | T
                | {
                    name?: T;
                    asset?: T;
                    src?: T;
                    alt?: T;
                    role?: T;
                    collaboration?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        buttonCards?:
          | T
          | {
              id?: T;
              header?: T;
              cards?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    description?: T;
                    image?: T;
                    button?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                          disabled?: T;
                          download?: T;
                        };
                    id?: T;
                  };
              footerNote?: T;
              blockName?: T;
            };
        downloadList?:
          | T
          | {
              id?: T;
              header?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    format?: T;
                    size?: T;
                    href?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              id?: T;
              sectionName?: T;
              header?: T;
              body?: T;
              variant?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              blockName?: T;
            };
        form?:
          | T
          | {
              id?: T;
              header?: T;
              intro?: T;
              description?: T;
              fields?:
                | T
                | {
                    name?: T;
                    label?: T;
                    type?: T;
                    placeholder?: T;
                    required?: T;
                    options?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              submitLabel?: T;
              submit?:
                | T
                | {
                    to?: T;
                    subject?: T;
                    successMessage?: T;
                  };
              contactNote?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              blockName?: T;
            };
        featuredStories?:
          | T
          | {
              id?: T;
              header?: T;
              layout?: T;
              main?:
                | T
                | {
                    tag?: T;
                    headline?: T;
                    excerpt?: T;
                    image?:
                      | T
                      | {
                          asset?: T;
                          src?: T;
                          alt?: T;
                          privacyBlur?: T;
                          caption?: T;
                        };
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                          disabled?: T;
                          download?: T;
                        };
                  };
              side?:
                | T
                | {
                    tag?: T;
                    headline?: T;
                    excerpt?: T;
                    image?:
                      | T
                      | {
                          asset?: T;
                          src?: T;
                          alt?: T;
                          privacyBlur?: T;
                          caption?: T;
                        };
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                          disabled?: T;
                          download?: T;
                        };
                    id?: T;
                  };
              blockName?: T;
            };
        pricing?:
          | T
          | {
              id?: T;
              header?: T;
              columns?:
                | T
                | {
                    title?: T;
                    sub?: T;
                    body?: T;
                    badge?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                          disabled?: T;
                          download?: T;
                        };
                    id?: T;
                  };
              blockName?: T;
            };
        galleryGrid?:
          | T
          | {
              id?: T;
              sectionName?: T;
              header?: T;
              intro?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              items?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    caption?: T;
                    image?:
                      | T
                      | {
                          asset?: T;
                          src?: T;
                          alt?: T;
                          privacyBlur?: T;
                          caption?: T;
                        };
                    id?: T;
                  };
              blockName?: T;
            };
        sitemap?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        metaStrip?:
          | T
          | {
              id?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        twoColumn?:
          | T
          | {
              id?: T;
              header?: T;
              intro?: T;
              variant?: T;
              compact?: T;
              left?:
                | T
                | {
                    heading?: T;
                    icon?: T;
                    lead?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          text?: T;
                          id?: T;
                        };
                  };
              right?:
                | T
                | {
                    heading?: T;
                    icon?: T;
                    lead?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          text?: T;
                          id?: T;
                        };
                  };
              footer?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    disabled?: T;
                    download?: T;
                  };
              blockName?: T;
            };
        relatedCards?:
          | T
          | {
              id?: T;
              header?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    href?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        patentGrid?:
          | T
          | {
              header?: T;
              intro?: T;
              filterNote?: T;
              patents?:
                | T
                | {
                    title?: T;
                    category?: T;
                    status?: T;
                    filingDate?: T;
                    ageGroup?: T;
                    applicationNo?: T;
                    inventors?: T;
                    description?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        profile?:
          | T
          | {
              id?: T;
              name?: T;
              role?: T;
              email?: T;
              image?:
                | T
                | {
                    asset?: T;
                    src?: T;
                    alt?: T;
                    privacyBlur?: T;
                    caption?: T;
                  };
              bio?: T;
              socials?:
                | T
                | {
                    type?: T;
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        glossaryAccordion?:
          | T
          | {
              header?: T;
              items?:
                | T
                | {
                    term?: T;
                    definition?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numberedCards?:
          | T
          | {
              id?: T;
              header?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        tierCards?:
          | T
          | {
              header?: T;
              tiers?:
                | T
                | {
                    label?: T;
                    title?: T;
                    subtitle?: T;
                    body?: T;
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    note?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                          disabled?: T;
                          download?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        toolCards?:
          | T
          | {
              header?: T;
              tools?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    body?: T;
                    details?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    downloads?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              header?: T;
              intro?: T;
              body?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tableBlock?:
          | T
          | {
              id?: T;
              header?: T;
              intro?: T;
              headers?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              blockName?: T;
            };
        anchorBlock?:
          | T
          | {
              id?: T;
              header?: T;
              body?: T;
              blockName?: T;
            };
        timelineSteps?:
          | T
          | {
              header?: T;
              steps?:
                | T
                | {
                    title?: T;
                    body?: T;
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pillars?:
          | T
          | {
              header?: T;
              items?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        frameworkPapers?:
          | T
          | {
              id?: T;
              header?: T;
              papers?:
                | T
                | {
                    title?: T;
                    doi?: T;
                    link?: T;
                    body?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        dossierHeader?:
          | T
          | {
              id?: T;
              title?: T;
              subtitle?: T;
              classification?: T;
              dataPanel?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        dossierSection?:
          | T
          | {
              id?: T;
              number?: T;
              label?: T;
              header?: T;
              body?: T;
              variant?: T;
              blockName?: T;
            };
        dossierQuoteStrip?:
          | T
          | {
              id?: T;
              quote?: T;
              blockName?: T;
            };
        dossierSpecTable?:
          | T
          | {
              id?: T;
              number?: T;
              label?: T;
              header?: T;
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        dossierTimeline?:
          | T
          | {
              id?: T;
              number?: T;
              label?: T;
              events?:
                | T
                | {
                    date?: T;
                    description?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        dossierNotice?:
          | T
          | {
              id?: T;
              label?: T;
              body?: T;
              blockName?: T;
            };
        dossierPrinciples?:
          | T
          | {
              id?: T;
              number?: T;
              label?: T;
              header?: T;
              intro?: T;
              principles?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              conclusion?: T;
              blockName?: T;
            };
        dossierGallery?:
          | T
          | {
              id?: T;
              number?: T;
              label?: T;
              images?:
                | T
                | {
                    asset?: T;
                    src?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        dossierArchiveNotice?:
          | T
          | {
              id?: T;
              body?: T;
              blockName?: T;
            };
        dossierRelated?:
          | T
          | {
              id?: T;
              header?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    href?: T;
                    id?: T;
                  };
              blockName?: T;
            };
      };
  stickyCta?:
    | T
    | {
        label?: T;
        href?: T;
        type?: T;
      };
  pageTitle?: T;
  metaDescription?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        keywords?: T;
        robots?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogType?: T;
        ogImage?: T;
        ogImageUrl?: T;
        ogImageAlt?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        twitterImageUrl?: T;
      };
  schemas?:
    | T
    | {
        label?: T;
        schema?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global brand, navigation, and contact details used site-wide.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  headerTagline?: string | null;
  /**
   * Shown below the logo in the website footer.
   */
  ethicsTagline?: string | null;
  logo?: (string | null) | Media;
  researchEmail?: string | null;
  pressEmail?: string | null;
  /**
   * Drag to reorder. Each item can have sub-menu children.
   */
  navigation?:
    | {
        label: string;
        /**
         * Use /path for internal links, or https://... for external.
         */
        path: string;
        /**
         * Optional icon shown next to the label.
         */
        icon?:
          | (
              | ''
              | 'home'
              | 'institute'
              | 'methodology'
              | 'publication'
              | 'governance'
              | 'collaborate'
              | 'newsroom'
              | 'contact'
              | 'lightbulb'
              | 'alert'
              | 'download'
              | 'database'
              | 'bookOpen'
              | 'team'
              | 'lock'
              | 'scale'
              | 'clipboardList'
              | 'badgeCheck'
              | 'microscope'
              | 'globe'
              | 'newspaper'
              | 'archive'
            )
          | null;
        external?: boolean | null;
        /**
         * Add dropdown items under this navigation link.
         */
        children?:
          | {
              label: string;
              path: string;
              icon?:
                | (
                    | ''
                    | 'home'
                    | 'institute'
                    | 'methodology'
                    | 'publication'
                    | 'governance'
                    | 'collaborate'
                    | 'newsroom'
                    | 'contact'
                    | 'lightbulb'
                    | 'alert'
                    | 'download'
                    | 'database'
                    | 'bookOpen'
                    | 'team'
                    | 'lock'
                    | 'scale'
                    | 'clipboardList'
                    | 'badgeCheck'
                    | 'microscope'
                    | 'globe'
                    | 'newspaper'
                    | 'archive'
                  )
                | null;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage footer social links, governance column, utility bar, and copyright.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings".
 */
export interface FooterSetting {
  id: string;
  /**
   * Shown in the footer brand column. Drag to reorder.
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'linkedin' | 'whatsapp' | 'twitter' | 'other';
        url: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Links in the Governance column on the right side of the footer.
   */
  governanceLinks?:
    | {
        label: string;
        path: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small links shown below the navigation columns.
   */
  utilityLinks?:
    | {
        label: string;
        path: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  schoolLink?: string | null;
  schoolLinkLabel?: string | null;
  /**
   * Leave blank to use: © {year} {Site Name}. All rights reserved.
   */
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  headerTagline?: T;
  ethicsTagline?: T;
  logo?: T;
  researchEmail?: T;
  pressEmail?: T;
  navigation?:
    | T
    | {
        label?: T;
        path?: T;
        icon?: T;
        external?: T;
        children?:
          | T
          | {
              label?: T;
              path?: T;
              icon?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  governanceLinks?:
    | T
    | {
        label?: T;
        path?: T;
        external?: T;
        id?: T;
      };
  utilityLinks?:
    | T
    | {
        label?: T;
        path?: T;
        external?: T;
        id?: T;
      };
  schoolLink?: T;
  schoolLinkLabel?: T;
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}